# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

use_frameworks!

target 'SwiftLibrariesPods' do
    pod 'Alamofire', '~> 2.0'
    pod 'SwiftyJSON', '= 2.2.1'
end

target 'SwiftLibrariesPodsTests' do

end

